version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-sample
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Admin1999
      - MYSQL_DATABASE=CFFE_Database
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - mysql-data:/var/lib/mysql
      - ./CFFE_DB.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    image: cffe:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  mysql-data: